// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// Interface for Groth16 verifier contracts generated by snarkjs
// Keeps the original type name to avoid changing imports/usages.
interface Groth16Verifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[5] calldata _pubSignals
    ) external view returns (bool);
}

